btnRegister="Register"
btnGender ="gender-male"
first_name = "FirstName"
last_name = "LastName"
selectDay = "DateOfBirthDay"
selectMonth = "DateOfBirthMonth"
selectYear = "DateOfBirthYear"
email = "Email"
newsLetter = "Newsletter"
inputPass = "Password"
confirmPass = "ConfirmPassword"
submit = "//button[@id='register-button']"
